version: '3'
services:
  client:
    build: client/
    ports:
      - 3000:3000
    # restart: unless-stopped
  server:
    build: server/
    # ports:
    #   - 5000:5000
    # restart: unless-stopped
    volumes:
      - ./storage:/app/storage
  proxy:
    image: nginx:1.17
    ports:
      - 8000:80
