version: '3'
services:
  client:
    build: client/
    # ports:
    #   - 3000:3000
    # restart: unless-stopped
    volumes:
      - ./staticFrontend:/app/build # Moves our build file we made in the container to the root dir under 'staticFrontend'
  server:
    build: server/
    # ports:
    #   - 5000:5000
    # restart: unless-stopped
    volumes:
      - ./storage:/app/storage # Give access to our storage file
  proxy:
    build: nginx/
    ports:
      - 80:80 # Expose port 80 to the outside world under port 80
    volumes:
      - ./staticFrontend:/staticFrontend:ro # Take our newly generated 'staticFrontend' for display use
      - ./storage:/storage:ro # We need nginx to see this folder so it can server new and old files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # For live updates
